/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package algo.hw;

import static org.junit.jupiter.api.Assertions.*;

import org.junit.jupiter.api.Test;

class SortTests {

    @Test
    public void MergeSortTest() {
        MergeSort m = new MergeSort();

        int[] test = {4, 3, 6, 1, 3};
        int[] sorted = {1,3,3,4,6};

        assertArrayEquals(m.sort(test), sorted);

        int[] lengthOneTest = {1};
        int[] lengthOneSorted = {1};

        assertArrayEquals(m.sort(lengthOneTest), lengthOneSorted);

        int[] lenZeroTest = {};
        int[] lenZeroSorted = {};

        assertArrayEquals(m.sort(lenZeroTest), lenZeroSorted);

        int[] backwardsTest = {5, 4, 3, 2, 1};
        int[] backwardsSorted = {1,2,3,4,5};

        assertArrayEquals(m.sort(backwardsTest), backwardsSorted);

        int[] repeatedTest = {5, 5, 5, 5, 5};

        assertArrayEquals(m.sort(repeatedTest), repeatedTest);
    }

    @Test
    public void BubbleSortTest() {
        BubbleSort bubble = new BubbleSort();

        int[] test = {4, 3, 6, 1, 3};
        int[] sorted = {1,3,3,4,6};

        assertArrayEquals(bubble.sort(test), sorted);

        int[] lengthOneTest = {1};
        int[] lengthOneSorted = {1};

        assertArrayEquals(bubble.sort(lengthOneTest), lengthOneSorted);

        int[] lenZeroTest = {};
        int[] lenZeroSorted = {};

        assertArrayEquals(bubble.sort(lenZeroTest), lenZeroSorted);

        int[] backwardsTest = {5, 4, 3, 2, 1};
        int[] backwardsSorted = {1,2,3,4,5};

        assertArrayEquals(bubble.sort(backwardsTest), backwardsSorted);

        int[] repeatedTest = {5, 5, 5, 5, 5};

        assertArrayEquals(bubble.sort(repeatedTest), repeatedTest);
    }
}